compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
num_processes: 3          
num_machines: 1
machine_rank: 0
gpu_ids: "0,1,2"

mixed_precision: bf16    

deepspeed_config:
  zero_stage: 3
  bf16: true
  
  offload_optimizer_device: "none"   
  offload_param_device: "none"       
  overlap_comm: true
  contiguous_gradients: true
  zero3_save_16bit_model: true

  gradient_accumulation_steps: 1
  steps_per_print: 100