data_dir: data/packed/rpjv2_s2048

train_micro_batch_size_per_gpu: 4
gradient_accumulation_steps: 1
pin_memory: true
num_workers: 8
prefetch_factor: 2
persistent_workers: true

learning_rate: 0.0002
betas: [0.9, 0.95]
weight_decay: 0.1
max_steps: 200
warmup_steps: 50

bf16: true
amp: false
gradient_checkpointing: true

save_interval: 50
eval_interval: 2000
logging_interval: 10
save_dir: checkpoints/qwen3_0.6b

seed: 42

